#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Essent
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EssentIAM")]
	public partial class DCWebDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblCustomDataEntry(tblCustomDataEntry instance);
    partial void UpdatetblCustomDataEntry(tblCustomDataEntry instance);
    partial void DeletetblCustomDataEntry(tblCustomDataEntry instance);
    #endregion
		
		public DCWebDataContext() : 
				base(global::Essent.Properties.Settings.Default.EssentIAMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCWebDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCWebDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCWebDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCWebDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblCustomDataEntry> tblCustomDataEntries
		{
			get
			{
				return this.GetTable<tblCustomDataEntry>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCustomDataEntry")]
	public partial class tblCustomDataEntry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _DataEntryID;
		
		private string _Barcode;
		
		private int _Klantnr_hoofdzetel;
		
		private int _Klantnummer;
		
		private string _Bestandsnaam;
		
		private string _Directory;
		
		private string _Dataveld1;
		
		private string _Dataveld2;
		
		private string _Dataveld3;
		
		private string _Dataveld4;
		
		private string _Dataveld5;
		
		private string _Dataveld6;
		
		private string _Dataveld7;
		
		private string _Dataveld8;
		
		private string _Dataveld9;
		
		private string _Dataveld10;
		
		private string _Dataveld11;
		
		private string _Dataveld12;
		
		private string _Dataveld13;
		
		private string _Dataveld14;
		
		private string _Dataveld15;
		
		private string _Dataveld16;
		
		private string _Dataveld17;
		
		private string _Dataveld18;
		
		private string _Dataveld19;
		
		private string _Dataveld20;
		
		private string _Dataveld21;
		
		private string _Dataveld22;
		
		private string _Dataveld23;
		
		private string _Dataveld24;
		
		private string _Dataveld25;
		
		private string _Dataveld26;
		
		private string _Dataveld27;
		
		private string _Dataveld28;
		
		private string _Dataveld29;
		
		private string _Dataveld30;
		
		private bool _To_Import;
		
		private bool _Beveiligd;
		
		private System.Nullable<System.DateTime> _Creatiedatum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDataEntryIDChanging(long value);
    partial void OnDataEntryIDChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnKlantnr_hoofdzetelChanging(int value);
    partial void OnKlantnr_hoofdzetelChanged();
    partial void OnKlantnummerChanging(int value);
    partial void OnKlantnummerChanged();
    partial void OnBestandsnaamChanging(string value);
    partial void OnBestandsnaamChanged();
    partial void OnDirectoryChanging(string value);
    partial void OnDirectoryChanged();
    partial void OnDataveld1Changing(string value);
    partial void OnDataveld1Changed();
    partial void OnDataveld2Changing(string value);
    partial void OnDataveld2Changed();
    partial void OnDataveld3Changing(string value);
    partial void OnDataveld3Changed();
    partial void OnDataveld4Changing(string value);
    partial void OnDataveld4Changed();
    partial void OnDataveld5Changing(string value);
    partial void OnDataveld5Changed();
    partial void OnDataveld6Changing(string value);
    partial void OnDataveld6Changed();
    partial void OnDataveld7Changing(string value);
    partial void OnDataveld7Changed();
    partial void OnDataveld8Changing(string value);
    partial void OnDataveld8Changed();
    partial void OnDataveld9Changing(string value);
    partial void OnDataveld9Changed();
    partial void OnDataveld10Changing(string value);
    partial void OnDataveld10Changed();
    partial void OnDataveld11Changing(string value);
    partial void OnDataveld11Changed();
    partial void OnDataveld12Changing(string value);
    partial void OnDataveld12Changed();
    partial void OnDataveld13Changing(string value);
    partial void OnDataveld13Changed();
    partial void OnDataveld14Changing(string value);
    partial void OnDataveld14Changed();
    partial void OnDataveld15Changing(string value);
    partial void OnDataveld15Changed();
    partial void OnDataveld16Changing(string value);
    partial void OnDataveld16Changed();
    partial void OnDataveld17Changing(string value);
    partial void OnDataveld17Changed();
    partial void OnDataveld18Changing(string value);
    partial void OnDataveld18Changed();
    partial void OnDataveld19Changing(string value);
    partial void OnDataveld19Changed();
    partial void OnDataveld20Changing(string value);
    partial void OnDataveld20Changed();
    partial void OnDataveld21Changing(string value);
    partial void OnDataveld21Changed();
    partial void OnDataveld22Changing(string value);
    partial void OnDataveld22Changed();
    partial void OnDataveld23Changing(string value);
    partial void OnDataveld23Changed();
    partial void OnDataveld24Changing(string value);
    partial void OnDataveld24Changed();
    partial void OnDataveld25Changing(string value);
    partial void OnDataveld25Changed();
    partial void OnDataveld26Changing(string value);
    partial void OnDataveld26Changed();
    partial void OnDataveld27Changing(string value);
    partial void OnDataveld27Changed();
    partial void OnDataveld28Changing(string value);
    partial void OnDataveld28Changed();
    partial void OnDataveld29Changing(string value);
    partial void OnDataveld29Changed();
    partial void OnDataveld30Changing(string value);
    partial void OnDataveld30Changed();
    partial void OnTo_ImportChanging(bool value);
    partial void OnTo_ImportChanged();
    partial void OnBeveiligdChanging(bool value);
    partial void OnBeveiligdChanged();
    partial void OnCreatiedatumChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatiedatumChanged();
    #endregion
		
		public tblCustomDataEntry()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEntryID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long DataEntryID
		{
			get
			{
				return this._DataEntryID;
			}
			set
			{
				if ((this._DataEntryID != value))
				{
					this.OnDataEntryIDChanging(value);
					this.SendPropertyChanging();
					this._DataEntryID = value;
					this.SendPropertyChanged("DataEntryID");
					this.OnDataEntryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="VarChar(30)")]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this.OnBarcodeChanging(value);
					this.SendPropertyChanging();
					this._Barcode = value;
					this.SendPropertyChanged("Barcode");
					this.OnBarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klantnr_hoofdzetel", DbType="Int NOT NULL")]
		public int Klantnr_hoofdzetel
		{
			get
			{
				return this._Klantnr_hoofdzetel;
			}
			set
			{
				if ((this._Klantnr_hoofdzetel != value))
				{
					this.OnKlantnr_hoofdzetelChanging(value);
					this.SendPropertyChanging();
					this._Klantnr_hoofdzetel = value;
					this.SendPropertyChanged("Klantnr_hoofdzetel");
					this.OnKlantnr_hoofdzetelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klantnummer", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Klantnummer
		{
			get
			{
				return this._Klantnummer;
			}
			set
			{
				if ((this._Klantnummer != value))
				{
					this.OnKlantnummerChanging(value);
					this.SendPropertyChanging();
					this._Klantnummer = value;
					this.SendPropertyChanged("Klantnummer");
					this.OnKlantnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bestandsnaam", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Bestandsnaam
		{
			get
			{
				return this._Bestandsnaam;
			}
			set
			{
				if ((this._Bestandsnaam != value))
				{
					this.OnBestandsnaamChanging(value);
					this.SendPropertyChanging();
					this._Bestandsnaam = value;
					this.SendPropertyChanged("Bestandsnaam");
					this.OnBestandsnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Directory", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Directory
		{
			get
			{
				return this._Directory;
			}
			set
			{
				if ((this._Directory != value))
				{
					this.OnDirectoryChanging(value);
					this.SendPropertyChanging();
					this._Directory = value;
					this.SendPropertyChanged("Directory");
					this.OnDirectoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld1", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Dataveld1
		{
			get
			{
				return this._Dataveld1;
			}
			set
			{
				if ((this._Dataveld1 != value))
				{
					this.OnDataveld1Changing(value);
					this.SendPropertyChanging();
					this._Dataveld1 = value;
					this.SendPropertyChanged("Dataveld1");
					this.OnDataveld1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld2", DbType="VarChar(255)")]
		public string Dataveld2
		{
			get
			{
				return this._Dataveld2;
			}
			set
			{
				if ((this._Dataveld2 != value))
				{
					this.OnDataveld2Changing(value);
					this.SendPropertyChanging();
					this._Dataveld2 = value;
					this.SendPropertyChanged("Dataveld2");
					this.OnDataveld2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld3", DbType="VarChar(8000)")]
		public string Dataveld3
		{
			get
			{
				return this._Dataveld3;
			}
			set
			{
				if ((this._Dataveld3 != value))
				{
					this.OnDataveld3Changing(value);
					this.SendPropertyChanging();
					this._Dataveld3 = value;
					this.SendPropertyChanged("Dataveld3");
					this.OnDataveld3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld4", DbType="VarChar(255)")]
		public string Dataveld4
		{
			get
			{
				return this._Dataveld4;
			}
			set
			{
				if ((this._Dataveld4 != value))
				{
					this.OnDataveld4Changing(value);
					this.SendPropertyChanging();
					this._Dataveld4 = value;
					this.SendPropertyChanged("Dataveld4");
					this.OnDataveld4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld5", DbType="VarChar(555)")]
		public string Dataveld5
		{
			get
			{
				return this._Dataveld5;
			}
			set
			{
				if ((this._Dataveld5 != value))
				{
					this.OnDataveld5Changing(value);
					this.SendPropertyChanging();
					this._Dataveld5 = value;
					this.SendPropertyChanged("Dataveld5");
					this.OnDataveld5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld6", DbType="VarChar(255)")]
		public string Dataveld6
		{
			get
			{
				return this._Dataveld6;
			}
			set
			{
				if ((this._Dataveld6 != value))
				{
					this.OnDataveld6Changing(value);
					this.SendPropertyChanging();
					this._Dataveld6 = value;
					this.SendPropertyChanged("Dataveld6");
					this.OnDataveld6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld7", DbType="VarChar(255)")]
		public string Dataveld7
		{
			get
			{
				return this._Dataveld7;
			}
			set
			{
				if ((this._Dataveld7 != value))
				{
					this.OnDataveld7Changing(value);
					this.SendPropertyChanging();
					this._Dataveld7 = value;
					this.SendPropertyChanged("Dataveld7");
					this.OnDataveld7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld8", DbType="VarChar(255)")]
		public string Dataveld8
		{
			get
			{
				return this._Dataveld8;
			}
			set
			{
				if ((this._Dataveld8 != value))
				{
					this.OnDataveld8Changing(value);
					this.SendPropertyChanging();
					this._Dataveld8 = value;
					this.SendPropertyChanged("Dataveld8");
					this.OnDataveld8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld9", DbType="VarChar(255)")]
		public string Dataveld9
		{
			get
			{
				return this._Dataveld9;
			}
			set
			{
				if ((this._Dataveld9 != value))
				{
					this.OnDataveld9Changing(value);
					this.SendPropertyChanging();
					this._Dataveld9 = value;
					this.SendPropertyChanged("Dataveld9");
					this.OnDataveld9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld10", DbType="VarChar(255)")]
		public string Dataveld10
		{
			get
			{
				return this._Dataveld10;
			}
			set
			{
				if ((this._Dataveld10 != value))
				{
					this.OnDataveld10Changing(value);
					this.SendPropertyChanging();
					this._Dataveld10 = value;
					this.SendPropertyChanged("Dataveld10");
					this.OnDataveld10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld11", DbType="VarChar(255)")]
		public string Dataveld11
		{
			get
			{
				return this._Dataveld11;
			}
			set
			{
				if ((this._Dataveld11 != value))
				{
					this.OnDataveld11Changing(value);
					this.SendPropertyChanging();
					this._Dataveld11 = value;
					this.SendPropertyChanged("Dataveld11");
					this.OnDataveld11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld12", DbType="VarChar(255)")]
		public string Dataveld12
		{
			get
			{
				return this._Dataveld12;
			}
			set
			{
				if ((this._Dataveld12 != value))
				{
					this.OnDataveld12Changing(value);
					this.SendPropertyChanging();
					this._Dataveld12 = value;
					this.SendPropertyChanged("Dataveld12");
					this.OnDataveld12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld13", DbType="VarChar(255)")]
		public string Dataveld13
		{
			get
			{
				return this._Dataveld13;
			}
			set
			{
				if ((this._Dataveld13 != value))
				{
					this.OnDataveld13Changing(value);
					this.SendPropertyChanging();
					this._Dataveld13 = value;
					this.SendPropertyChanged("Dataveld13");
					this.OnDataveld13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld14", DbType="VarChar(255)")]
		public string Dataveld14
		{
			get
			{
				return this._Dataveld14;
			}
			set
			{
				if ((this._Dataveld14 != value))
				{
					this.OnDataveld14Changing(value);
					this.SendPropertyChanging();
					this._Dataveld14 = value;
					this.SendPropertyChanged("Dataveld14");
					this.OnDataveld14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld15", DbType="VarChar(255)")]
		public string Dataveld15
		{
			get
			{
				return this._Dataveld15;
			}
			set
			{
				if ((this._Dataveld15 != value))
				{
					this.OnDataveld15Changing(value);
					this.SendPropertyChanging();
					this._Dataveld15 = value;
					this.SendPropertyChanged("Dataveld15");
					this.OnDataveld15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld16", DbType="VarChar(255)")]
		public string Dataveld16
		{
			get
			{
				return this._Dataveld16;
			}
			set
			{
				if ((this._Dataveld16 != value))
				{
					this.OnDataveld16Changing(value);
					this.SendPropertyChanging();
					this._Dataveld16 = value;
					this.SendPropertyChanged("Dataveld16");
					this.OnDataveld16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld17", DbType="VarChar(255)")]
		public string Dataveld17
		{
			get
			{
				return this._Dataveld17;
			}
			set
			{
				if ((this._Dataveld17 != value))
				{
					this.OnDataveld17Changing(value);
					this.SendPropertyChanging();
					this._Dataveld17 = value;
					this.SendPropertyChanged("Dataveld17");
					this.OnDataveld17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld18", DbType="VarChar(255)")]
		public string Dataveld18
		{
			get
			{
				return this._Dataveld18;
			}
			set
			{
				if ((this._Dataveld18 != value))
				{
					this.OnDataveld18Changing(value);
					this.SendPropertyChanging();
					this._Dataveld18 = value;
					this.SendPropertyChanged("Dataveld18");
					this.OnDataveld18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld19", DbType="VarChar(255)")]
		public string Dataveld19
		{
			get
			{
				return this._Dataveld19;
			}
			set
			{
				if ((this._Dataveld19 != value))
				{
					this.OnDataveld19Changing(value);
					this.SendPropertyChanging();
					this._Dataveld19 = value;
					this.SendPropertyChanged("Dataveld19");
					this.OnDataveld19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld20", DbType="VarChar(255)")]
		public string Dataveld20
		{
			get
			{
				return this._Dataveld20;
			}
			set
			{
				if ((this._Dataveld20 != value))
				{
					this.OnDataveld20Changing(value);
					this.SendPropertyChanging();
					this._Dataveld20 = value;
					this.SendPropertyChanged("Dataveld20");
					this.OnDataveld20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld21", DbType="VarChar(255)")]
		public string Dataveld21
		{
			get
			{
				return this._Dataveld21;
			}
			set
			{
				if ((this._Dataveld21 != value))
				{
					this.OnDataveld21Changing(value);
					this.SendPropertyChanging();
					this._Dataveld21 = value;
					this.SendPropertyChanged("Dataveld21");
					this.OnDataveld21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld22", DbType="VarChar(255)")]
		public string Dataveld22
		{
			get
			{
				return this._Dataveld22;
			}
			set
			{
				if ((this._Dataveld22 != value))
				{
					this.OnDataveld22Changing(value);
					this.SendPropertyChanging();
					this._Dataveld22 = value;
					this.SendPropertyChanged("Dataveld22");
					this.OnDataveld22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld23", DbType="VarChar(255)")]
		public string Dataveld23
		{
			get
			{
				return this._Dataveld23;
			}
			set
			{
				if ((this._Dataveld23 != value))
				{
					this.OnDataveld23Changing(value);
					this.SendPropertyChanging();
					this._Dataveld23 = value;
					this.SendPropertyChanged("Dataveld23");
					this.OnDataveld23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld24", DbType="VarChar(255)")]
		public string Dataveld24
		{
			get
			{
				return this._Dataveld24;
			}
			set
			{
				if ((this._Dataveld24 != value))
				{
					this.OnDataveld24Changing(value);
					this.SendPropertyChanging();
					this._Dataveld24 = value;
					this.SendPropertyChanged("Dataveld24");
					this.OnDataveld24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld25", DbType="VarChar(255)")]
		public string Dataveld25
		{
			get
			{
				return this._Dataveld25;
			}
			set
			{
				if ((this._Dataveld25 != value))
				{
					this.OnDataveld25Changing(value);
					this.SendPropertyChanging();
					this._Dataveld25 = value;
					this.SendPropertyChanged("Dataveld25");
					this.OnDataveld25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld26", DbType="VarChar(255)")]
		public string Dataveld26
		{
			get
			{
				return this._Dataveld26;
			}
			set
			{
				if ((this._Dataveld26 != value))
				{
					this.OnDataveld26Changing(value);
					this.SendPropertyChanging();
					this._Dataveld26 = value;
					this.SendPropertyChanged("Dataveld26");
					this.OnDataveld26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld27", DbType="VarChar(255)")]
		public string Dataveld27
		{
			get
			{
				return this._Dataveld27;
			}
			set
			{
				if ((this._Dataveld27 != value))
				{
					this.OnDataveld27Changing(value);
					this.SendPropertyChanging();
					this._Dataveld27 = value;
					this.SendPropertyChanged("Dataveld27");
					this.OnDataveld27Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld28", DbType="VarChar(255)")]
		public string Dataveld28
		{
			get
			{
				return this._Dataveld28;
			}
			set
			{
				if ((this._Dataveld28 != value))
				{
					this.OnDataveld28Changing(value);
					this.SendPropertyChanging();
					this._Dataveld28 = value;
					this.SendPropertyChanged("Dataveld28");
					this.OnDataveld28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld29", DbType="VarChar(255)")]
		public string Dataveld29
		{
			get
			{
				return this._Dataveld29;
			}
			set
			{
				if ((this._Dataveld29 != value))
				{
					this.OnDataveld29Changing(value);
					this.SendPropertyChanging();
					this._Dataveld29 = value;
					this.SendPropertyChanged("Dataveld29");
					this.OnDataveld29Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dataveld30", DbType="VarChar(255)")]
		public string Dataveld30
		{
			get
			{
				return this._Dataveld30;
			}
			set
			{
				if ((this._Dataveld30 != value))
				{
					this.OnDataveld30Changing(value);
					this.SendPropertyChanging();
					this._Dataveld30 = value;
					this.SendPropertyChanged("Dataveld30");
					this.OnDataveld30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Import", DbType="Bit NOT NULL")]
		public bool To_Import
		{
			get
			{
				return this._To_Import;
			}
			set
			{
				if ((this._To_Import != value))
				{
					this.OnTo_ImportChanging(value);
					this.SendPropertyChanging();
					this._To_Import = value;
					this.SendPropertyChanged("To_Import");
					this.OnTo_ImportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beveiligd", DbType="Bit NOT NULL")]
		public bool Beveiligd
		{
			get
			{
				return this._Beveiligd;
			}
			set
			{
				if ((this._Beveiligd != value))
				{
					this.OnBeveiligdChanging(value);
					this.SendPropertyChanging();
					this._Beveiligd = value;
					this.SendPropertyChanged("Beveiligd");
					this.OnBeveiligdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creatiedatum", DbType="DateTime")]
		public System.Nullable<System.DateTime> Creatiedatum
		{
			get
			{
				return this._Creatiedatum;
			}
			set
			{
				if ((this._Creatiedatum != value))
				{
					this.OnCreatiedatumChanging(value);
					this.SendPropertyChanging();
					this._Creatiedatum = value;
					this.SendPropertyChanged("Creatiedatum");
					this.OnCreatiedatumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
